#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Igetis

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Struct_food1_structs.hpp"
#include "Struct_prop_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function igetis.igetis_C.ExecuteUbergraph_igetis
// 0x07A0 (0x07A0 - 0x0000)
struct Igetis_C_ExecuteUbergraph_igetis final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x0004(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable_1;                              // 0x000C(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0020(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0030(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0038(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_2;            // 0x0048(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x0058(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_4;                   // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_3;                   // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_3;            // 0x0070(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_2;                   // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_4;            // 0x0088(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_1;                   // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_5;            // 0x00A0(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName;                     // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_6;            // 0x00B8(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   Temp_name_Variable_2;                              // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MultiplyMultiply_FloatFloat_ReturnValue;  // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x00D4(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_MultiplyMultiply_FloatFloat_ReturnValue_1; // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_2;        // 0x00E8(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MultiplyMultiply_FloatFloat_ReturnValue_2; // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Ease_ReturnValue;                         // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Lerp_ReturnValue;                         // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_FD[0x3];                                       // 0x00FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Ease_ReturnValue_1;                       // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Lerp_ReturnValue_1;                       // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x3];                                      // 0x0109(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Ease_ReturnValue_2;                       // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_2;                    // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_111[0x3];                                      // 0x0111(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Lerp_ReturnValue_2;                       // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11D[0x3];                                      // 0x011D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_1;           // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_129[0x3];                                      // 0x0129(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_propToObject_ReturnValue;                 // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_131[0x3];                                      // 0x0131(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_food1                          CallFunc_propToObject_foodData;                    // 0x0134(0x0018)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14C[0x4];                                      // 0x014C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_propToObject_object;                      // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_propToObject_isFood;                      // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_159[0x7];                                      // 0x0159(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_prop                           CallFunc_propToObject_propData;                    // 0x0160(0x0080)(HasGetValueTypeHash)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E1[0x3];                                      // 0x01E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_4;                               // 0x01E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_5;                               // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_2;           // 0x01EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1ED[0x3];                                      // 0x01ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x01F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x01F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_1;  // 0x01F8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_1;           // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_1;            // 0x0208(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_1;       // 0x0210(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep_1;           // 0x0214(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_215[0x3];                                      // 0x0215(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult_1;          // 0x0218(0x0088)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsMain_Player;             // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B1[0x7];                                      // 0x02B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AKavotia_C*                             CallFunc_Array_Get_Item;                           // 0x02B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x02C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x02C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C5[0x3];                                      // 0x02C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerCameraManager*                   CallFunc_GetPlayerCameraManager_ReturnValue;       // 0x02C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x02D0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x02DC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Vector_Distance2D_ReturnValue;            // 0x02E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x02EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2ED[0x3];                                      // 0x02ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerCameraManager*                   CallFunc_GetPlayerCameraManager_ReturnValue_1;     // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_2;        // 0x02F8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_3;        // 0x0304(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Vector_Distance2D_ReturnValue_1;          // 0x0310(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_314[0x4];                                      // 0x0314(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0318(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0320(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0328(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0330(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x0334(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_335[0x3];                                      // 0x0335(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0338(0x0088)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x03C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3C1[0x7];                                      // 0x03C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue; // 0x03C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x03D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D1[0xF];                                      // 0x03D1(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x03E0(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_TLerp_ReturnValue;                        // 0x0410(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_1;     // 0x0440(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_2;     // 0x0470(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_3;     // 0x04A0(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_TLerp_ReturnValue_1;                      // 0x04D0(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult;      // 0x0500(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_588[0x8];                                      // 0x0588(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_4;     // 0x0590(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x05C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x05C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5D4[0x4];                                      // 0x05D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x05D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x05E0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5EC[0x4];                                      // 0x05EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IInt_player_C>         K2Node_DynamicCast_AsInt_Player;                   // 0x05F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0600(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_601[0x7];                                      // 0x0601(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1; // 0x0608(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AProp_C*                                CallFunc_asProp_return;                            // 0x0610(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x0618(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class AProp_C*                                CallFunc_FinishSpawningActor_ReturnValue_1;        // 0x0628(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2; // 0x0630(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AProp_food_C*                           CallFunc_FinishSpawningActor_ReturnValue_2;        // 0x0638(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Select_Default;                             // 0x0640(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IInt_player_C>         K2Node_DynamicCast_AsInt_Player_1;                 // 0x0648(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0658(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_659[0x7];                                      // 0x0659(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_5;     // 0x0660(0x0030)(IsPlainOldData, NoDestructor)
	class AProp_C*                                CallFunc_asProp_return_1;                          // 0x0690(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_698[0x8];                                      // 0x0698(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_TLerp_ReturnValue_2;                      // 0x06A0(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult_1;    // 0x06D0(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0758(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue_1; // 0x0760(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Condition_2;                    // 0x0768(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_Condition_1;                    // 0x0769(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_76A[0x2];                                      // 0x076A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x076C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x0778(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Condition;                      // 0x0784(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_785[0x3];                                      // 0x0785(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue_2; // 0x0788(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_2;    // 0x0790(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Igetis_C_ExecuteUbergraph_igetis) == 0x000010, "Wrong alignment on Igetis_C_ExecuteUbergraph_igetis");
static_assert(sizeof(Igetis_C_ExecuteUbergraph_igetis) == 0x0007A0, "Wrong size on Igetis_C_ExecuteUbergraph_igetis");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, EntryPoint) == 0x000000, "Member 'Igetis_C_ExecuteUbergraph_igetis::EntryPoint' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, Temp_name_Variable) == 0x000004, "Member 'Igetis_C_ExecuteUbergraph_igetis::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, Temp_name_Variable_1) == 0x00000C, "Member 'Igetis_C_ExecuteUbergraph_igetis::Temp_name_Variable_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, Temp_int_Variable) == 0x000014, "Member 'Igetis_C_ExecuteUbergraph_igetis::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, Temp_int_Variable_1) == 0x000018, "Member 'Igetis_C_ExecuteUbergraph_igetis::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Add_IntInt_ReturnValue) == 0x00001C, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CreateDelegate_OutputDelegate) == 0x000020, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000030, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CreateDelegate_OutputDelegate_1) == 0x000038, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CreateDelegate_OutputDelegate_2) == 0x000048, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x000058, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CustomEvent_NotifyName_4) == 0x000060, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CustomEvent_NotifyName_4' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CustomEvent_NotifyName_3) == 0x000068, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CustomEvent_NotifyName_3' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CreateDelegate_OutputDelegate_3) == 0x000070, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CustomEvent_NotifyName_2) == 0x000080, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CustomEvent_NotifyName_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CreateDelegate_OutputDelegate_4) == 0x000088, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CustomEvent_NotifyName_1) == 0x000098, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CustomEvent_NotifyName_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CreateDelegate_OutputDelegate_5) == 0x0000A0, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CustomEvent_NotifyName) == 0x0000B0, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CustomEvent_NotifyName' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CreateDelegate_OutputDelegate_6) == 0x0000B8, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, Temp_name_Variable_2) == 0x0000C8, "Member 'Igetis_C_ExecuteUbergraph_igetis::Temp_name_Variable_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_MultiplyMultiply_FloatFloat_ReturnValue) == 0x0000D0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_MultiplyMultiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CreateDelegate_OutputDelegate_7) == 0x0000D4, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_MultiplyMultiply_FloatFloat_ReturnValue_1) == 0x0000E4, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_MultiplyMultiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_SetTimerDelegate_ReturnValue_2) == 0x0000E8, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_SetTimerDelegate_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_MultiplyMultiply_FloatFloat_ReturnValue_2) == 0x0000F0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_MultiplyMultiply_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Ease_ReturnValue) == 0x0000F4, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Ease_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Lerp_ReturnValue) == 0x0000F8, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Lerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_SwitchEnum_CmpSuccess) == 0x0000FC, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Ease_ReturnValue_1) == 0x000100, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Ease_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Lerp_ReturnValue_1) == 0x000104, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Lerp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_SwitchEnum_CmpSuccess_1) == 0x000108, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_SwitchEnum_CmpSuccess_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Ease_ReturnValue_2) == 0x00010C, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Ease_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_SwitchEnum_CmpSuccess_2) == 0x000110, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_SwitchEnum_CmpSuccess_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Lerp_ReturnValue_2) == 0x000114, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Lerp_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, Temp_int_Variable_2) == 0x000118, "Member 'Igetis_C_ExecuteUbergraph_igetis::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_LessEqual_IntInt_ReturnValue) == 0x00011C, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Add_IntInt_ReturnValue_1) == 0x000120, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, Temp_int_Variable_3) == 0x000124, "Member 'Igetis_C_ExecuteUbergraph_igetis::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_LessEqual_IntInt_ReturnValue_1) == 0x000128, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_LessEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Add_IntInt_ReturnValue_2) == 0x00012C, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_propToObject_ReturnValue) == 0x000130, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_propToObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_propToObject_foodData) == 0x000134, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_propToObject_foodData' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_propToObject_object) == 0x000150, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_propToObject_object' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_propToObject_isFood) == 0x000158, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_propToObject_isFood' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_propToObject_propData) == 0x000160, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_propToObject_propData' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_IsValidClass_ReturnValue) == 0x0001E0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, Temp_int_Variable_4) == 0x0001E4, "Member 'Igetis_C_ExecuteUbergraph_igetis::Temp_int_Variable_4' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, Temp_int_Variable_5) == 0x0001E8, "Member 'Igetis_C_ExecuteUbergraph_igetis::Temp_int_Variable_5' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_LessEqual_IntInt_ReturnValue_2) == 0x0001EC, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_LessEqual_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Add_IntInt_ReturnValue_3) == 0x0001F0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_Event_DeltaSeconds) == 0x0001F4, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_OverlappedComponent_1) == 0x0001F8, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_OverlappedComponent_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_OtherActor_1) == 0x000200, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_OtherComp_1) == 0x000208, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_OtherBodyIndex_1) == 0x000210, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_OtherBodyIndex_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_bFromSweep_1) == 0x000214, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_bFromSweep_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_SweepResult_1) == 0x000218, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_SweepResult_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_GetObjectClass_ReturnValue) == 0x0002A0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ClassDynamicCast_AsMain_Player) == 0x0002A8, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ClassDynamicCast_AsMain_Player' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ClassDynamicCast_bSuccess) == 0x0002B0, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Array_Get_Item) == 0x0002B8, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Array_Length_ReturnValue) == 0x0002C0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Less_IntInt_ReturnValue) == 0x0002C4, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_GetPlayerCameraManager_ReturnValue) == 0x0002C8, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_GetPlayerCameraManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0002D0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x0002DC, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Vector_Distance2D_ReturnValue) == 0x0002E8, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Vector_Distance2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Greater_FloatFloat_ReturnValue) == 0x0002EC, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_GetPlayerCameraManager_ReturnValue_1) == 0x0002F0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_GetPlayerCameraManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetActorLocation_ReturnValue_2) == 0x0002F8, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetActorLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetActorLocation_ReturnValue_3) == 0x000304, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetActorLocation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Vector_Distance2D_ReturnValue_1) == 0x000310, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Vector_Distance2D_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000318, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_OtherActor) == 0x000320, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_OtherComp) == 0x000328, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000330, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_bFromSweep) == 0x000334, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_ComponentBoundEvent_SweepResult) == 0x000338, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x0003C0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue) == 0x0003C8, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_IsValid_ReturnValue) == 0x0003D0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x0003E0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_TLerp_ReturnValue) == 0x000410, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_TLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetComponentToWorld_ReturnValue_1) == 0x000440, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetComponentToWorld_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetComponentToWorld_ReturnValue_2) == 0x000470, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetComponentToWorld_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetComponentToWorld_ReturnValue_3) == 0x0004A0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetComponentToWorld_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_TLerp_ReturnValue_1) == 0x0004D0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_TLerp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_SetWorldTransform_SweepHitResult) == 0x000500, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_SetWorldTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetComponentToWorld_ReturnValue_4) == 0x000590, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetComponentToWorld_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0005C0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_GetForwardVector_ReturnValue) == 0x0005C8, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_FinishSpawningActor_ReturnValue) == 0x0005D8, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x0005E0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_DynamicCast_AsInt_Player) == 0x0005F0, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_DynamicCast_AsInt_Player' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_DynamicCast_bSuccess) == 0x000600, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1) == 0x000608, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_asProp_return) == 0x000610, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_asProp_return' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_Conv_NameToString_ReturnValue) == 0x000618, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_FinishSpawningActor_ReturnValue_1) == 0x000628, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_FinishSpawningActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2) == 0x000630, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_FinishSpawningActor_ReturnValue_2) == 0x000638, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_FinishSpawningActor_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_Select_Default) == 0x000640, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_DynamicCast_AsInt_Player_1) == 0x000648, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_DynamicCast_AsInt_Player_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_DynamicCast_bSuccess_1) == 0x000658, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetComponentToWorld_ReturnValue_5) == 0x000660, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetComponentToWorld_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_asProp_return_1) == 0x000690, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_asProp_return_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_TLerp_ReturnValue_2) == 0x0006A0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_TLerp_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_SetWorldTransform_SweepHitResult_1) == 0x0006D0, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_SetWorldTransform_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x000758, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_CreateDynamicMaterialInstance_ReturnValue_1) == 0x000760, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_CreateDynamicMaterialInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CustomEvent_Condition_2) == 0x000768, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CustomEvent_Condition_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CustomEvent_Condition_1) == 0x000769, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CustomEvent_Condition_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x00076C, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x000778, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, K2Node_CustomEvent_Condition) == 0x000784, "Member 'Igetis_C_ExecuteUbergraph_igetis::K2Node_CustomEvent_Condition' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_CreateDynamicMaterialInstance_ReturnValue_2) == 0x000788, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_CreateDynamicMaterialInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Igetis_C_ExecuteUbergraph_igetis, CallFunc_K2_GetComponentLocation_ReturnValue_2) == 0x000790, "Member 'Igetis_C_ExecuteUbergraph_igetis::CallFunc_K2_GetComponentLocation_ReturnValue_2' has a wrong offset!");

// Function igetis.igetis_C.beamPut
// 0x0001 (0x0001 - 0x0000)
struct Igetis_C_beamPut final
{
public:
	bool                                          Condition;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Igetis_C_beamPut) == 0x000001, "Wrong alignment on Igetis_C_beamPut");
static_assert(sizeof(Igetis_C_beamPut) == 0x000001, "Wrong size on Igetis_C_beamPut");
static_assert(offsetof(Igetis_C_beamPut, Condition) == 0x000000, "Member 'Igetis_C_beamPut::Condition' has a wrong offset!");

// Function igetis.igetis_C.beamOn2
// 0x0001 (0x0001 - 0x0000)
struct Igetis_C_beamOn2 final
{
public:
	bool                                          Condition;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Igetis_C_beamOn2) == 0x000001, "Wrong alignment on Igetis_C_beamOn2");
static_assert(sizeof(Igetis_C_beamOn2) == 0x000001, "Wrong size on Igetis_C_beamOn2");
static_assert(offsetof(Igetis_C_beamOn2, Condition) == 0x000000, "Member 'Igetis_C_beamOn2::Condition' has a wrong offset!");

// Function igetis.igetis_C.beamOn1
// 0x0001 (0x0001 - 0x0000)
struct Igetis_C_beamOn1 final
{
public:
	bool                                          Condition;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Igetis_C_beamOn1) == 0x000001, "Wrong alignment on Igetis_C_beamOn1");
static_assert(sizeof(Igetis_C_beamOn1) == 0x000001, "Wrong size on Igetis_C_beamOn1");
static_assert(offsetof(Igetis_C_beamOn1, Condition) == 0x000000, "Member 'Igetis_C_beamOn1::Condition' has a wrong offset!");

// Function igetis.igetis_C.BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// 0x00A8 (0x00A8 - 0x0000)
struct Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x0000A8, "Wrong size on Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'Igetis_C_BndEvt__igetis_Sphere1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function igetis.igetis_C.BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x00A8 (0x00A8 - 0x0000)
struct Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x0000A8, "Wrong size on Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'Igetis_C_BndEvt__igetis_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function igetis.igetis_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct Igetis_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Igetis_C_ReceiveTick) == 0x000004, "Wrong alignment on Igetis_C_ReceiveTick");
static_assert(sizeof(Igetis_C_ReceiveTick) == 0x000004, "Wrong size on Igetis_C_ReceiveTick");
static_assert(offsetof(Igetis_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'Igetis_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function igetis.igetis_C.OnCompleted_1F02E3C54A95B9529AC8DE8ED5E6A6C9
// 0x0008 (0x0008 - 0x0000)
struct Igetis_C_OnCompleted_1F02E3C54A95B9529AC8DE8ED5E6A6C9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Igetis_C_OnCompleted_1F02E3C54A95B9529AC8DE8ED5E6A6C9) == 0x000004, "Wrong alignment on Igetis_C_OnCompleted_1F02E3C54A95B9529AC8DE8ED5E6A6C9");
static_assert(sizeof(Igetis_C_OnCompleted_1F02E3C54A95B9529AC8DE8ED5E6A6C9) == 0x000008, "Wrong size on Igetis_C_OnCompleted_1F02E3C54A95B9529AC8DE8ED5E6A6C9");
static_assert(offsetof(Igetis_C_OnCompleted_1F02E3C54A95B9529AC8DE8ED5E6A6C9, NotifyName) == 0x000000, "Member 'Igetis_C_OnCompleted_1F02E3C54A95B9529AC8DE8ED5E6A6C9::NotifyName' has a wrong offset!");

// Function igetis.igetis_C.OnBlendOut_1F02E3C54A95B9529AC8DE8ED5E6A6C9
// 0x0008 (0x0008 - 0x0000)
struct Igetis_C_OnBlendOut_1F02E3C54A95B9529AC8DE8ED5E6A6C9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Igetis_C_OnBlendOut_1F02E3C54A95B9529AC8DE8ED5E6A6C9) == 0x000004, "Wrong alignment on Igetis_C_OnBlendOut_1F02E3C54A95B9529AC8DE8ED5E6A6C9");
static_assert(sizeof(Igetis_C_OnBlendOut_1F02E3C54A95B9529AC8DE8ED5E6A6C9) == 0x000008, "Wrong size on Igetis_C_OnBlendOut_1F02E3C54A95B9529AC8DE8ED5E6A6C9");
static_assert(offsetof(Igetis_C_OnBlendOut_1F02E3C54A95B9529AC8DE8ED5E6A6C9, NotifyName) == 0x000000, "Member 'Igetis_C_OnBlendOut_1F02E3C54A95B9529AC8DE8ED5E6A6C9::NotifyName' has a wrong offset!");

// Function igetis.igetis_C.OnInterrupted_1F02E3C54A95B9529AC8DE8ED5E6A6C9
// 0x0008 (0x0008 - 0x0000)
struct Igetis_C_OnInterrupted_1F02E3C54A95B9529AC8DE8ED5E6A6C9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Igetis_C_OnInterrupted_1F02E3C54A95B9529AC8DE8ED5E6A6C9) == 0x000004, "Wrong alignment on Igetis_C_OnInterrupted_1F02E3C54A95B9529AC8DE8ED5E6A6C9");
static_assert(sizeof(Igetis_C_OnInterrupted_1F02E3C54A95B9529AC8DE8ED5E6A6C9) == 0x000008, "Wrong size on Igetis_C_OnInterrupted_1F02E3C54A95B9529AC8DE8ED5E6A6C9");
static_assert(offsetof(Igetis_C_OnInterrupted_1F02E3C54A95B9529AC8DE8ED5E6A6C9, NotifyName) == 0x000000, "Member 'Igetis_C_OnInterrupted_1F02E3C54A95B9529AC8DE8ED5E6A6C9::NotifyName' has a wrong offset!");

// Function igetis.igetis_C.OnNotifyBegin_1F02E3C54A95B9529AC8DE8ED5E6A6C9
// 0x0008 (0x0008 - 0x0000)
struct Igetis_C_OnNotifyBegin_1F02E3C54A95B9529AC8DE8ED5E6A6C9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Igetis_C_OnNotifyBegin_1F02E3C54A95B9529AC8DE8ED5E6A6C9) == 0x000004, "Wrong alignment on Igetis_C_OnNotifyBegin_1F02E3C54A95B9529AC8DE8ED5E6A6C9");
static_assert(sizeof(Igetis_C_OnNotifyBegin_1F02E3C54A95B9529AC8DE8ED5E6A6C9) == 0x000008, "Wrong size on Igetis_C_OnNotifyBegin_1F02E3C54A95B9529AC8DE8ED5E6A6C9");
static_assert(offsetof(Igetis_C_OnNotifyBegin_1F02E3C54A95B9529AC8DE8ED5E6A6C9, NotifyName) == 0x000000, "Member 'Igetis_C_OnNotifyBegin_1F02E3C54A95B9529AC8DE8ED5E6A6C9::NotifyName' has a wrong offset!");

// Function igetis.igetis_C.OnNotifyEnd_1F02E3C54A95B9529AC8DE8ED5E6A6C9
// 0x0008 (0x0008 - 0x0000)
struct Igetis_C_OnNotifyEnd_1F02E3C54A95B9529AC8DE8ED5E6A6C9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Igetis_C_OnNotifyEnd_1F02E3C54A95B9529AC8DE8ED5E6A6C9) == 0x000004, "Wrong alignment on Igetis_C_OnNotifyEnd_1F02E3C54A95B9529AC8DE8ED5E6A6C9");
static_assert(sizeof(Igetis_C_OnNotifyEnd_1F02E3C54A95B9529AC8DE8ED5E6A6C9) == 0x000008, "Wrong size on Igetis_C_OnNotifyEnd_1F02E3C54A95B9529AC8DE8ED5E6A6C9");
static_assert(offsetof(Igetis_C_OnNotifyEnd_1F02E3C54A95B9529AC8DE8ED5E6A6C9, NotifyName) == 0x000000, "Member 'Igetis_C_OnNotifyEnd_1F02E3C54A95B9529AC8DE8ED5E6A6C9::NotifyName' has a wrong offset!");

// Function igetis.igetis_C.tryDelete
// 0x0028 (0x0028 - 0x0000)
struct Igetis_C_TryDelete final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_WasRecentlyRendered_ReturnValue;          // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AKavotia_C*                             CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Igetis_C_TryDelete) == 0x000008, "Wrong alignment on Igetis_C_TryDelete");
static_assert(sizeof(Igetis_C_TryDelete) == 0x000028, "Wrong size on Igetis_C_TryDelete");
static_assert(offsetof(Igetis_C_TryDelete, Temp_int_Array_Index_Variable) == 0x000000, "Member 'Igetis_C_TryDelete::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Igetis_C_TryDelete, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'Igetis_C_TryDelete::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Igetis_C_TryDelete, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'Igetis_C_TryDelete::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_TryDelete, CallFunc_WasRecentlyRendered_ReturnValue) == 0x00000C, "Member 'Igetis_C_TryDelete::CallFunc_WasRecentlyRendered_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_TryDelete, CallFunc_Array_Length_ReturnValue) == 0x000010, "Member 'Igetis_C_TryDelete::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_TryDelete, CallFunc_Array_Get_Item) == 0x000018, "Member 'Igetis_C_TryDelete::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Igetis_C_TryDelete, CallFunc_Less_IntInt_ReturnValue) == 0x000020, "Member 'Igetis_C_TryDelete::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Igetis_C_TryDelete, CallFunc_IsValid_ReturnValue) == 0x000021, "Member 'Igetis_C_TryDelete::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

