#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Int_playerInput

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass int_playerInput.int_playerInput_C
// 0x0000 (0x0028 - 0x0028)
class IInt_playerInput_C final : public IInterface
{
public:
	void ScrollUp();
	void ScrollDown();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"int_playerInput_C">();
	}
	static class IInt_playerInput_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IInt_playerInput_C>();
	}
};
static_assert(alignof(IInt_playerInput_C) == 0x000008, "Wrong alignment on IInt_playerInput_C");
static_assert(sizeof(IInt_playerInput_C) == 0x000028, "Wrong size on IInt_playerInput_C");

}

