#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewBlueprint15

#include "Basic.hpp"

#include "NewBlueprint15_classes.hpp"
#include "NewBlueprint15_parameters.hpp"


namespace SDK
{

// Function NewBlueprint15.NewBlueprint15_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ANewBlueprint15_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewBlueprint15_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewBlueprint15.NewBlueprint15_C.Min
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FIntVector                       Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewBlueprint15_C::Min(const struct FIntVector& Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewBlueprint15_C", "Min");

	Params::NewBlueprint15_C_Min Parms{};

	Parms.Time = std::move(Time);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewBlueprint15.NewBlueprint15_C.ExecuteUbergraph_NewBlueprint15
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewBlueprint15_C::ExecuteUbergraph_NewBlueprint15(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewBlueprint15_C", "ExecuteUbergraph_NewBlueprint15");

	Params::NewBlueprint15_C_ExecuteUbergraph_NewBlueprint15 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

