#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_coalVein

#include "Basic.hpp"

#include "Prop_coalVein_classes.hpp"
#include "Prop_coalVein_parameters.hpp"


namespace SDK
{

// Function prop_coalVein.prop_coalVein_C.ExecuteUbergraph_prop_coalVein
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AProp_coalVein_C::ExecuteUbergraph_prop_coalVein(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("prop_coalVein_C", "ExecuteUbergraph_prop_coalVein");

	Params::Prop_coalVein_C_ExecuteUbergraph_prop_coalVein Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function prop_coalVein.prop_coalVein_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AProp_coalVein_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("prop_coalVein_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function prop_coalVein.prop_coalVein_C.damageByPlayer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMainPlayer_C*                    Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Param_Hit                                              (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AProp_coalVein_C::DamageByPlayer(class AMainPlayer_C* Player, const struct FHitResult& Param_Hit, float Damage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("prop_coalVein_C", "damageByPlayer");

	Params::Prop_coalVein_C_DamageByPlayer Parms{};

	Parms.Player = Player;
	Parms.Param_Hit = std::move(Param_Hit);
	Parms.Damage = Damage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function prop_coalVein.prop_coalVein_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AProp_coalVein_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("prop_coalVein_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

