#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_rifle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Prop_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass prop_rifle.prop_rifle_C
// 0x0008 (0x0370 - 0x0368)
class AProp_rifle_C final : public AProp_C
{
public:
	uint8                                         Pad_3CD0[0x7];                                     // 0x0361(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_Prop_rifle_C;                       // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_prop_rifle(int32 EntryPoint);
	void PlayerHandUse_LMB(class AMainPlayer_C* Player);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"prop_rifle_C">();
	}
	static class AProp_rifle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_rifle_C>();
	}
};
static_assert(alignof(AProp_rifle_C) == 0x000008, "Wrong alignment on AProp_rifle_C");
static_assert(sizeof(AProp_rifle_C) == 0x000370, "Wrong size on AProp_rifle_C");
static_assert(offsetof(AProp_rifle_C, UberGraphFrame_Prop_rifle_C) == 0x000368, "Member 'AProp_rifle_C::UberGraphFrame_Prop_rifle_C' has a wrong offset!");

}

