#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_scubaTank

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Prop_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass prop_scubaTank.prop_scubaTank_C
// 0x0010 (0x0388 - 0x0378)
class AProp_scubaTank_C final : public AProp_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Prop_scubaTank_C;                   // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         Fuel;                                              // 0x0380(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_prop_scubaTank(int32 EntryPoint);
	void PlayerHandUse_LMB(class AMainPlayer_C* Player);
	void LookAt(class AMainPlayer_C* Player, const struct FHitResult& Param_Hit, bool* Return, class FString* Text, class UPrimitiveComponent** boundObjectReplace, uint8* Number);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"prop_scubaTank_C">();
	}
	static class AProp_scubaTank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_scubaTank_C>();
	}
};
static_assert(alignof(AProp_scubaTank_C) == 0x000008, "Wrong alignment on AProp_scubaTank_C");
static_assert(sizeof(AProp_scubaTank_C) == 0x000388, "Wrong size on AProp_scubaTank_C");
static_assert(offsetof(AProp_scubaTank_C, UberGraphFrame_Prop_scubaTank_C) == 0x000378, "Member 'AProp_scubaTank_C::UberGraphFrame_Prop_scubaTank_C' has a wrong offset!");
static_assert(offsetof(AProp_scubaTank_C, Fuel) == 0x000380, "Member 'AProp_scubaTank_C::Fuel' has a wrong offset!");

}

