#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_radBarrel

#include "Basic.hpp"

#include "Prop_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass prop_radBarrel.prop_radBarrel_C
// 0x0008 (0x0370 - 0x0368)
class AProp_radBarrel_C final : public AProp_C
{
public:
	uint8                                         Pad_380B[0x7];                                     // 0x0361(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URadiationComponent_C*                  RadComp;                                           // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"prop_radBarrel_C">();
	}
	static class AProp_radBarrel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_radBarrel_C>();
	}
};
static_assert(alignof(AProp_radBarrel_C) == 0x000008, "Wrong alignment on AProp_radBarrel_C");
static_assert(sizeof(AProp_radBarrel_C) == 0x000370, "Wrong size on AProp_radBarrel_C");
static_assert(offsetof(AProp_radBarrel_C, RadComp) == 0x000368, "Member 'AProp_radBarrel_C::RadComp' has a wrong offset!");

}

