#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_slab_0

#include "Basic.hpp"

#include "Prop_slab_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass prop_slab_0.prop_slab_0_C
// 0x0000 (0x0370 - 0x0370)
class AProp_slab_0_C final : public AProp_slab_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"prop_slab_0_C">();
	}
	static class AProp_slab_0_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_slab_0_C>();
	}
};
static_assert(alignof(AProp_slab_0_C) == 0x000008, "Wrong alignment on AProp_slab_0_C");
static_assert(sizeof(AProp_slab_0_C) == 0x000370, "Wrong size on AProp_slab_0_C");

}

