#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_knife

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Prop_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass prop_knife.prop_knife_C
// 0x0010 (0x0388 - 0x0378)
class AProp_knife_C final : public AProp_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Prop_knife_C;                       // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVelocityStuck_C*                       VelocityStuck;                                     // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_prop_knife(int32 EntryPoint);
	void ReceiveBeginPlay();
	void PlayerHandUse_LMB(class AMainPlayer_C* Player);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"prop_knife_C">();
	}
	static class AProp_knife_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_knife_C>();
	}
};
static_assert(alignof(AProp_knife_C) == 0x000008, "Wrong alignment on AProp_knife_C");
static_assert(sizeof(AProp_knife_C) == 0x000388, "Wrong size on AProp_knife_C");
static_assert(offsetof(AProp_knife_C, UberGraphFrame_Prop_knife_C) == 0x000378, "Member 'AProp_knife_C::UberGraphFrame_Prop_knife_C' has a wrong offset!");
static_assert(offsetof(AProp_knife_C, VelocityStuck) == 0x000380, "Member 'AProp_knife_C::VelocityStuck' has a wrong offset!");

}

