#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_food_potato

#include "Basic.hpp"

#include "Prop_food_potato_classes.hpp"
#include "Prop_food_potato_parameters.hpp"


namespace SDK
{

// Function prop_food_potato.prop_food_potato_C.cooked
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AProp_food_potato_C::Cooked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("prop_food_potato_C", "cooked");

	UObject::ProcessEvent(Func, nullptr);
}

}

