#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_ubaitBox_3

#include "Basic.hpp"

#include "Prop_ubaitBox_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass prop_ubaitBox_3.prop_ubaitBox_3_C
// 0x0000 (0x0380 - 0x0380)
class AProp_ubaitBox_3_C final : public AProp_ubaitBox_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"prop_ubaitBox_3_C">();
	}
	static class AProp_ubaitBox_3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_ubaitBox_3_C>();
	}
};
static_assert(alignof(AProp_ubaitBox_3_C) == 0x000008, "Wrong alignment on AProp_ubaitBox_3_C");
static_assert(sizeof(AProp_ubaitBox_3_C) == 0x000380, "Wrong size on AProp_ubaitBox_3_C");

}

