#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_lifeCrystal

#include "Basic.hpp"

#include "Prop_lifeCrystal_classes.hpp"
#include "Prop_lifeCrystal_parameters.hpp"


namespace SDK
{

// Function prop_lifeCrystal.prop_lifeCrystal_C.ExecuteUbergraph_prop_lifeCrystal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AProp_lifeCrystal_C::ExecuteUbergraph_prop_lifeCrystal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("prop_lifeCrystal_C", "ExecuteUbergraph_prop_lifeCrystal");

	Params::Prop_lifeCrystal_C_ExecuteUbergraph_prop_lifeCrystal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function prop_lifeCrystal.prop_lifeCrystal_C.damageByPlayer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMainPlayer_C*                    Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Param_Hit                                              (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AProp_lifeCrystal_C::DamageByPlayer(class AMainPlayer_C* Player, const struct FHitResult& Param_Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("prop_lifeCrystal_C", "damageByPlayer");

	Params::Prop_lifeCrystal_C_DamageByPlayer Parms{};

	Parms.Player = Player;
	Parms.Param_Hit = std::move(Param_Hit);

	UObject::ProcessEvent(Func, &Parms);
}

}

