#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_dingus

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Struct_save_structs.hpp"
#include "Struct_mBool_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Enum_interactionActions_structs.hpp"


namespace SDK::Params
{

// Function prop_dingus.prop_dingus_C.ExecuteUbergraph_prop_dingus
// 0x0280 (0x0280 - 0x0000)
struct Prop_dingus_C_ExecuteUbergraph_prop_dingus final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F8E[0x3];                                     // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_1;           // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F8F[0x3];                                     // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_4;                               // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_5;                               // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_6;                               // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_2;           // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F90[0x3];                                     // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_3;           // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F91[0x3];                                     // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMainPlayer_C*                          K2Node_Event_player_1;                             // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_hit;                                  // 0x0050(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	int32                                         K2Node_Event_index;                                // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_interactionActions                       K2Node_Event_action;                               // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F92[0x3];                                     // 0x00DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AMainPlayer_C*                          K2Node_Event_player;                               // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F93[0x7];                                     // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AWaterVolume_C*                         K2Node_Event_water;                                // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F94[0x8];                                     // 0x00F8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0100(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AProp_dingusDies_C*                     CallFunc_FinishSpawningActor_ReturnValue;          // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMainGamemode_C*                        CallFunc_getMainGamemode_AsMain_Gamemode;          // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_6;                 // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x014C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VictoryFloatPlusEquals_FloatOut;          // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0154(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F95[0x3];                                     // 0x0155(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_7;                               // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_RandomUnitVector_ReturnValue;             // 0x015C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0168(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0174(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_RandomRotator_ReturnValue;                // 0x0180(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F96[0x4];                                     // 0x018C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0190(0x0030)(IsPlainOldData, NoDestructor)
	class UStaticMeshComponent*                   CallFunc_AddComponent_ReturnValue;                 // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x01C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F97[0xC];                                     // 0x01D4(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_1;              // 0x01E0(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1; // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AExplosion_C*                           CallFunc_FinishSpawningActor_ReturnValue_1;        // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMainGamemode_C*                        CallFunc_getMainGamemode_AsMain_Gamemode_1;        // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_7;                 // 0x0228(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x022C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item;                           // 0x0230(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0238(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x023C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F98[0x3];                                     // 0x023D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_RandomUnitVector_ReturnValue_1;           // 0x0240(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x024C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item_1;                         // 0x0250(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue_1;       // 0x0258(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0264(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F99[0x3];                                     // 0x0269(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetWorldDeltaSeconds_ReturnValue;         // 0x026C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0270(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VictoryFloatMinusEquals_FloatOut;         // 0x0274(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FMax_ReturnValue;                         // 0x0278(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_dingus_C_ExecuteUbergraph_prop_dingus) == 0x000010, "Wrong alignment on Prop_dingus_C_ExecuteUbergraph_prop_dingus");
static_assert(sizeof(Prop_dingus_C_ExecuteUbergraph_prop_dingus) == 0x000280, "Wrong size on Prop_dingus_C_ExecuteUbergraph_prop_dingus");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, EntryPoint) == 0x000000, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::EntryPoint' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, Temp_int_Variable) == 0x000004, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, Temp_int_Variable_1) == 0x00000C, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000010, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Add_IntInt_ReturnValue_1) == 0x000014, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, Temp_int_Variable_2) == 0x000018, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Add_IntInt_ReturnValue_2) == 0x00001C, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, Temp_int_Variable_3) == 0x000020, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_LessEqual_IntInt_ReturnValue_1) == 0x000024, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_LessEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Add_IntInt_ReturnValue_3) == 0x000028, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, Temp_int_Variable_4) == 0x00002C, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::Temp_int_Variable_4' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, Temp_int_Variable_5) == 0x000030, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::Temp_int_Variable_5' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, Temp_int_Variable_6) == 0x000034, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::Temp_int_Variable_6' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_LessEqual_IntInt_ReturnValue_2) == 0x000038, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_LessEqual_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Add_IntInt_ReturnValue_4) == 0x00003C, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_LessEqual_IntInt_ReturnValue_3) == 0x000040, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_LessEqual_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Add_IntInt_ReturnValue_5) == 0x000044, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, K2Node_Event_player_1) == 0x000048, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::K2Node_Event_player_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, K2Node_Event_hit) == 0x000050, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::K2Node_Event_hit' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, K2Node_Event_index) == 0x0000D8, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::K2Node_Event_index' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, K2Node_Event_action) == 0x0000DC, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::K2Node_Event_action' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, K2Node_Event_player) == 0x0000E0, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::K2Node_Event_player' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, K2Node_SwitchEnum_CmpSuccess) == 0x0000E8, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, K2Node_Event_water) == 0x0000F0, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::K2Node_Event_water' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_GetTransform_ReturnValue) == 0x000100, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000130, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_FinishSpawningActor_ReturnValue) == 0x000138, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_getMainGamemode_AsMain_Gamemode) == 0x000140, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_getMainGamemode_AsMain_Gamemode' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Add_IntInt_ReturnValue_6) == 0x000148, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Add_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Add_FloatFloat_ReturnValue) == 0x00014C, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_VictoryFloatPlusEquals_FloatOut) == 0x000150, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_VictoryFloatPlusEquals_FloatOut' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000154, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, Temp_int_Variable_7) == 0x000158, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::Temp_int_Variable_7' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_RandomUnitVector_ReturnValue) == 0x00015C, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_RandomUnitVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000168, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Add_VectorVector_ReturnValue) == 0x000174, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_RandomRotator_ReturnValue) == 0x000180, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_RandomRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_MakeTransform_ReturnValue) == 0x000190, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_AddComponent_ReturnValue) == 0x0001C0, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_AddComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x0001C8, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_MakeTransform_ReturnValue_1) == 0x0001E0, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_MakeTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1) == 0x000210, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_FinishSpawningActor_ReturnValue_1) == 0x000218, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_FinishSpawningActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_getMainGamemode_AsMain_Gamemode_1) == 0x000220, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_getMainGamemode_AsMain_Gamemode_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Add_IntInt_ReturnValue_7) == 0x000228, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Add_IntInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Array_Add_ReturnValue) == 0x00022C, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Array_Get_Item) == 0x000230, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Array_Length_ReturnValue) == 0x000238, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Less_IntInt_ReturnValue) == 0x00023C, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_RandomUnitVector_ReturnValue_1) == 0x000240, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_RandomUnitVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_RandomFloatInRange_ReturnValue) == 0x00024C, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Array_Get_Item_1) == 0x000250, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Multiply_VectorFloat_ReturnValue_1) == 0x000258, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Multiply_VectorFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Array_Length_ReturnValue_1) == 0x000264, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Less_IntInt_ReturnValue_1) == 0x000268, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_GetWorldDeltaSeconds_ReturnValue) == 0x00026C, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_GetWorldDeltaSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000270, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_VictoryFloatMinusEquals_FloatOut) == 0x000274, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_VictoryFloatMinusEquals_FloatOut' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ExecuteUbergraph_prop_dingus, CallFunc_FMax_ReturnValue) == 0x000278, "Member 'Prop_dingus_C_ExecuteUbergraph_prop_dingus::CallFunc_FMax_ReturnValue' has a wrong offset!");

// Function prop_dingus.prop_dingus_C.actionOptionIndex
// 0x0098 (0x0098 - 0x0000)
struct Prop_dingus_C_ActionOptionIndex final
{
public:
	class AMainPlayer_C*                          Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Param_Hit;                                         // 0x0008(0x0088)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	int32                                         Param_Index;                                       // 0x0090(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_interactionActions                       Action;                                            // 0x0094(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_dingus_C_ActionOptionIndex) == 0x000008, "Wrong alignment on Prop_dingus_C_ActionOptionIndex");
static_assert(sizeof(Prop_dingus_C_ActionOptionIndex) == 0x000098, "Wrong size on Prop_dingus_C_ActionOptionIndex");
static_assert(offsetof(Prop_dingus_C_ActionOptionIndex, Player) == 0x000000, "Member 'Prop_dingus_C_ActionOptionIndex::Player' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ActionOptionIndex, Param_Hit) == 0x000008, "Member 'Prop_dingus_C_ActionOptionIndex::Param_Hit' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ActionOptionIndex, Param_Index) == 0x000090, "Member 'Prop_dingus_C_ActionOptionIndex::Param_Index' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_ActionOptionIndex, Action) == 0x000094, "Member 'Prop_dingus_C_ActionOptionIndex::Action' has a wrong offset!");

// Function prop_dingus.prop_dingus_C.enterWater
// 0x0008 (0x0008 - 0x0000)
struct Prop_dingus_C_EnterWater final
{
public:
	class AWaterVolume_C*                         Water;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_dingus_C_EnterWater) == 0x000008, "Wrong alignment on Prop_dingus_C_EnterWater");
static_assert(sizeof(Prop_dingus_C_EnterWater) == 0x000008, "Wrong size on Prop_dingus_C_EnterWater");
static_assert(offsetof(Prop_dingus_C_EnterWater, Water) == 0x000000, "Member 'Prop_dingus_C_EnterWater::Water' has a wrong offset!");

// Function prop_dingus.prop_dingus_C.playerHandUse_RMB
// 0x0008 (0x0008 - 0x0000)
struct Prop_dingus_C_PlayerHandUse_RMB final
{
public:
	class AMainPlayer_C*                          Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_dingus_C_PlayerHandUse_RMB) == 0x000008, "Wrong alignment on Prop_dingus_C_PlayerHandUse_RMB");
static_assert(sizeof(Prop_dingus_C_PlayerHandUse_RMB) == 0x000008, "Wrong size on Prop_dingus_C_PlayerHandUse_RMB");
static_assert(offsetof(Prop_dingus_C_PlayerHandUse_RMB, Player) == 0x000000, "Member 'Prop_dingus_C_PlayerHandUse_RMB::Player' has a wrong offset!");

// Function prop_dingus.prop_dingus_C.getActionOptions
// 0x0058 (0x0058 - 0x0000)
struct Prop_dingus_C_GetActionOptions final
{
public:
	class AMainPlayer_C*                          Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    Component;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Actor;                                             // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         Options;                                           // 0x0018(0x0010)(Parm, OutParm)
	TArray<Enum_interactionActions>               Options_enum;                                      // 0x0028(0x0010)(Parm, OutParm)
	TArray<class FText>                           OptionsNamesOverlay;                               // 0x0038(0x0010)(Parm, OutParm)
	TArray<Enum_interactionActions>               K2Node_MakeArray_Array;                            // 0x0048(0x0010)(ReferenceParm)
};
static_assert(alignof(Prop_dingus_C_GetActionOptions) == 0x000008, "Wrong alignment on Prop_dingus_C_GetActionOptions");
static_assert(sizeof(Prop_dingus_C_GetActionOptions) == 0x000058, "Wrong size on Prop_dingus_C_GetActionOptions");
static_assert(offsetof(Prop_dingus_C_GetActionOptions, Player) == 0x000000, "Member 'Prop_dingus_C_GetActionOptions::Player' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetActionOptions, Component) == 0x000008, "Member 'Prop_dingus_C_GetActionOptions::Component' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetActionOptions, Actor) == 0x000010, "Member 'Prop_dingus_C_GetActionOptions::Actor' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetActionOptions, Options) == 0x000018, "Member 'Prop_dingus_C_GetActionOptions::Options' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetActionOptions, Options_enum) == 0x000028, "Member 'Prop_dingus_C_GetActionOptions::Options_enum' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetActionOptions, OptionsNamesOverlay) == 0x000038, "Member 'Prop_dingus_C_GetActionOptions::OptionsNamesOverlay' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetActionOptions, K2Node_MakeArray_Array) == 0x000048, "Member 'Prop_dingus_C_GetActionOptions::K2Node_MakeArray_Array' has a wrong offset!");

// Function prop_dingus.prop_dingus_C.lookAt
// 0x00B0 (0x00B0 - 0x0000)
struct Prop_dingus_C_LookAt final
{
public:
	class AMainPlayer_C*                          Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Param_Hit;                                         // 0x0008(0x0088)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          Return;                                            // 0x0090(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F9A[0x7];                                     // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Text;                                              // 0x0098(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    boundObjectReplace;                                // 0x00A8(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_dingus_C_LookAt) == 0x000008, "Wrong alignment on Prop_dingus_C_LookAt");
static_assert(sizeof(Prop_dingus_C_LookAt) == 0x0000B0, "Wrong size on Prop_dingus_C_LookAt");
static_assert(offsetof(Prop_dingus_C_LookAt, Player) == 0x000000, "Member 'Prop_dingus_C_LookAt::Player' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_LookAt, Param_Hit) == 0x000008, "Member 'Prop_dingus_C_LookAt::Param_Hit' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_LookAt, Return) == 0x000090, "Member 'Prop_dingus_C_LookAt::Return' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_LookAt, Text) == 0x000098, "Member 'Prop_dingus_C_LookAt::Text' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_LookAt, boundObjectReplace) == 0x0000A8, "Member 'Prop_dingus_C_LookAt::boundObjectReplace' has a wrong offset!");

// Function prop_dingus.prop_dingus_C.getData
// 0x0280 (0x0280 - 0x0000)
struct Prop_dingus_C_GetData final
{
public:
	struct FStruct_save                           Data;                                              // 0x0000(0x00C0)(Parm, OutParm, HasGetValueTypeHash)
	struct FStruct_save                           CallFunc_getData_data;                             // 0x00C0(0x00C0)(HasGetValueTypeHash)
	TArray<bool>                                  K2Node_MakeArray_Array;                            // 0x0180(0x0010)(ReferenceParm)
	struct FStruct_mBool                          K2Node_MakeStruct_struct_mBool;                    // 0x0190(0x0010)(HasGetValueTypeHash)
	struct FStruct_mBool                          CallFunc_Array_Get_Item;                           // 0x01A0(0x0010)(HasGetValueTypeHash)
	TArray<struct FStruct_mBool>                  K2Node_MakeArray_Array_1;                          // 0x01B0(0x0010)(ReferenceParm)
	struct FStruct_save                           K2Node_SetFieldsInStruct_StructOut;                // 0x01C0(0x00C0)(HasGetValueTypeHash)
};
static_assert(alignof(Prop_dingus_C_GetData) == 0x000010, "Wrong alignment on Prop_dingus_C_GetData");
static_assert(sizeof(Prop_dingus_C_GetData) == 0x000280, "Wrong size on Prop_dingus_C_GetData");
static_assert(offsetof(Prop_dingus_C_GetData, Data) == 0x000000, "Member 'Prop_dingus_C_GetData::Data' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetData, CallFunc_getData_data) == 0x0000C0, "Member 'Prop_dingus_C_GetData::CallFunc_getData_data' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetData, K2Node_MakeArray_Array) == 0x000180, "Member 'Prop_dingus_C_GetData::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetData, K2Node_MakeStruct_struct_mBool) == 0x000190, "Member 'Prop_dingus_C_GetData::K2Node_MakeStruct_struct_mBool' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetData, CallFunc_Array_Get_Item) == 0x0001A0, "Member 'Prop_dingus_C_GetData::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetData, K2Node_MakeArray_Array_1) == 0x0001B0, "Member 'Prop_dingus_C_GetData::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_GetData, K2Node_SetFieldsInStruct_StructOut) == 0x0001C0, "Member 'Prop_dingus_C_GetData::K2Node_SetFieldsInStruct_StructOut' has a wrong offset!");

// Function prop_dingus.prop_dingus_C.loadData
// 0x00E0 (0x00E0 - 0x0000)
struct Prop_dingus_C_LoadData final
{
public:
	struct FStruct_save                           Data;                                              // 0x0000(0x00C0)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	bool                                          Return;                                            // 0x00C0(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F9B[0x7];                                     // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_mBool                          CallFunc_Array_Get_Item;                           // 0x00C8(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_loadData_return;                          // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_Get_Item_1;                         // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Prop_dingus_C_LoadData) == 0x000010, "Wrong alignment on Prop_dingus_C_LoadData");
static_assert(sizeof(Prop_dingus_C_LoadData) == 0x0000E0, "Wrong size on Prop_dingus_C_LoadData");
static_assert(offsetof(Prop_dingus_C_LoadData, Data) == 0x000000, "Member 'Prop_dingus_C_LoadData::Data' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_LoadData, Return) == 0x0000C0, "Member 'Prop_dingus_C_LoadData::Return' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_LoadData, CallFunc_Array_Get_Item) == 0x0000C8, "Member 'Prop_dingus_C_LoadData::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_LoadData, CallFunc_loadData_return) == 0x0000D8, "Member 'Prop_dingus_C_LoadData::CallFunc_loadData_return' has a wrong offset!");
static_assert(offsetof(Prop_dingus_C_LoadData, CallFunc_Array_Get_Item_1) == 0x0000D9, "Member 'Prop_dingus_C_LoadData::CallFunc_Array_Get_Item_1' has a wrong offset!");

}

