#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_help

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct struct_help.struct_help
// 0x0030 (0x0030 - 0x0000)
struct FStruct_help final
{
public:
	class FText                                   Name_2_50E0B5FF49B11852CC54278F6F7E8017;           // 0x0000(0x0018)(Edit, BlueprintVisible)
	class FText                                   Description_4_C25F0DBC4A902D71BC78A889861CE2E9;    // 0x0018(0x0018)(Edit, BlueprintVisible)
};
static_assert(alignof(FStruct_help) == 0x000008, "Wrong alignment on FStruct_help");
static_assert(sizeof(FStruct_help) == 0x000030, "Wrong size on FStruct_help");
static_assert(offsetof(FStruct_help, Name_2_50E0B5FF49B11852CC54278F6F7E8017) == 0x000000, "Member 'FStruct_help::Name_2_50E0B5FF49B11852CC54278F6F7E8017' has a wrong offset!");
static_assert(offsetof(FStruct_help, Description_4_C25F0DBC4A902D71BC78A889861CE2E9) == 0x000018, "Member 'FStruct_help::Description_4_C25F0DBC4A902D71BC78A889861CE2E9' has a wrong offset!");

}

