#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trigger_box_N

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Trigger_box_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass trigger_box_N.trigger_box_N_C
// 0x0010 (0x02D0 - 0x02C0)
class ATrigger_box_N_C final : public ATrigger_box_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Trigger_box_N_C;                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         N;                                                 // 0x02C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void GetTriggerData(struct FStruct_triggerSave* Data);
	void LoadTriggerData(const struct FStruct_triggerSave& Data, bool* Return);
	void BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void ExecuteUbergraph_trigger_box_N(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"trigger_box_N_C">();
	}
	static class ATrigger_box_N_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATrigger_box_N_C>();
	}
};
static_assert(alignof(ATrigger_box_N_C) == 0x000008, "Wrong alignment on ATrigger_box_N_C");
static_assert(sizeof(ATrigger_box_N_C) == 0x0002D0, "Wrong size on ATrigger_box_N_C");
static_assert(offsetof(ATrigger_box_N_C, UberGraphFrame_Trigger_box_N_C) == 0x0002C0, "Member 'ATrigger_box_N_C::UberGraphFrame_Trigger_box_N_C' has a wrong offset!");
static_assert(offsetof(ATrigger_box_N_C, N) == 0x0002C8, "Member 'ATrigger_box_N_C::N' has a wrong offset!");

}

