#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Umg_spawnmenu

#include "Basic.hpp"

#include "Umg_spawnmenu_classes.hpp"
#include "Umg_spawnmenu_parameters.hpp"


namespace SDK
{

// Function umg_spawnmenu.umg_spawnmenu_C.ExecuteUbergraph_umg_spawnmenu
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUmg_spawnmenu_C::ExecuteUbergraph_umg_spawnmenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "ExecuteUbergraph_umg_spawnmenu");

	Params::Umg_spawnmenu_C_ExecuteUbergraph_umg_spawnmenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_checkbox_cat_mods_K2Node_ComponentBoundEvent_6_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_checkbox_cat_mods_K2Node_ComponentBoundEvent_6_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_checkbox_cat_mods_K2Node_ComponentBoundEvent_6_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_checkbox_cat_mods_K2Node_ComponentBoundEvent_6_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_checkbox_cat_tools_K2Node_ComponentBoundEvent_3_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_checkbox_cat_tools_K2Node_ComponentBoundEvent_3_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_checkbox_cat_tools_K2Node_ComponentBoundEvent_3_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_checkbox_cat_tools_K2Node_ComponentBoundEvent_3_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_checkbox_cat_wip_K2Node_ComponentBoundEvent_11_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_checkbox_cat_wip_K2Node_ComponentBoundEvent_11_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_checkbox_cat_wip_K2Node_ComponentBoundEvent_11_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_checkbox_cat_wip_K2Node_ComponentBoundEvent_11_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_checkbox_cat_signals_K2Node_ComponentBoundEvent_10_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_checkbox_cat_signals_K2Node_ComponentBoundEvent_10_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_checkbox_cat_signals_K2Node_ComponentBoundEvent_10_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_checkbox_cat_signals_K2Node_ComponentBoundEvent_10_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_checkbox_cat_props_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_checkbox_cat_props_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_checkbox_cat_props_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_checkbox_cat_props_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_checkbox_cat_misc_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_checkbox_cat_misc_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_checkbox_cat_misc_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_checkbox_cat_misc_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_checkbox_cat_food_K2Node_ComponentBoundEvent_7_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_checkbox_cat_food_K2Node_ComponentBoundEvent_7_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_checkbox_cat_food_K2Node_ComponentBoundEvent_7_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_checkbox_cat_food_K2Node_ComponentBoundEvent_7_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_checkbox_cat_ents_K2Node_ComponentBoundEvent_4_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_checkbox_cat_ents_K2Node_ComponentBoundEvent_4_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_checkbox_cat_ents_K2Node_ComponentBoundEvent_4_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_checkbox_cat_ents_K2Node_ComponentBoundEvent_4_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_checkbox_cat_dynamic_K2Node_ComponentBoundEvent_3_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_checkbox_cat_dynamic_K2Node_ComponentBoundEvent_3_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_checkbox_cat_dynamic_K2Node_ComponentBoundEvent_3_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_checkbox_cat_dynamic_K2Node_ComponentBoundEvent_3_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_CheckBox_spoiler_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_CheckBox_spoiler_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_CheckBox_spoiler_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_CheckBox_spoiler_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_Button_186_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_Button_186_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_Button_186_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function umg_spawnmenu.umg_spawnmenu_C.BndEvt__umg_spawnmenu_textbox_search_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUmg_spawnmenu_C::BndEvt__umg_spawnmenu_textbox_search_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "BndEvt__umg_spawnmenu_textbox_search_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature");

	Params::Umg_spawnmenu_C_BndEvt__umg_spawnmenu_textbox_search_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUmg_spawnmenu_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "Tick");

	Params::Umg_spawnmenu_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUmg_spawnmenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function umg_spawnmenu.umg_spawnmenu_C.Spawn
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Param_Name                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Ype                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UClass*                           S1                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FStruct_prop                     Data                                                   (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UUmg_spawnmenu_C::Spawn(class FName Param_Name, int32 Ype, class UClass* S1, const struct FStruct_prop& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "Spawn");

	Params::Umg_spawnmenu_C_Spawn Parms{};

	Parms.Param_Name = Param_Name;
	Parms.Ype = Ype;
	Parms.S1 = S1;
	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.SetName
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UUmg_spawnmenu_C::SetName(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "SetName");

	Params::Umg_spawnmenu_C_SetName Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawnmenu.umg_spawnmenu_C.filterList
// (Public, BlueprintCallable, BlueprintEvent)

void UUmg_spawnmenu_C::FilterList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawnmenu_C", "filterList");

	UObject::ProcessEvent(Func, nullptr);
}

}

