#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WarpArrowAppearShake

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass warpArrowAppearShake.warpArrowAppearShake_C
// 0x0000 (0x01B0 - 0x01B0)
class UWarpArrowAppearShake_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"warpArrowAppearShake_C">();
	}
	static class UWarpArrowAppearShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWarpArrowAppearShake_C>();
	}
};
static_assert(alignof(UWarpArrowAppearShake_C) == 0x000010, "Wrong alignment on UWarpArrowAppearShake_C");
static_assert(sizeof(UWarpArrowAppearShake_C) == 0x0001B0, "Wrong size on UWarpArrowAppearShake_C");

}

